version: "3.9"

networks:
  pinapp_rquirpa_net:
    name: pinapp_rquirpa_net

services:
  postgres:
    image: postgres:16.6
    container_name: postgres_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pinapp_rquirpa_net

  localstack:
    image: localstack/localstack:3.3
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - pinapp_rquirpa_net

volumes:
  pgdata:
  localstack_data:
